package com.affinity.awas.constants;

public enum CodeEnum {
	FEEDBACK_INVALID_STATUS("FEEDBACK_INVALID_STATUS"),
	FEEDBACK_INVALID_USER("FEEDBACK_INVALID_USER"),
	SCHEDULE_APPROVED("SCHEDULE_APPROVED"),
	SCHEDULE_CANCELLED("SCHEDULE_CANCELLED"),
	REQUEST_INVALID("REQUEST_INVALID"),
	REQUEST_EMPTY("REQUEST_EMPTY"),
	PERSON_INVALID("PERSON_INVALID"),
	SCHDULE_BOOKED("SCHDULE_BOOKED"),
	SCHEDULE_INVALID("SCHEDULE_INVALID"),
	SUCCESSFUL_SAVE("SUCCESSFUL_SAVE"),
	UNSUCCESSFUL_SAVE("UNSUCCESSFUL_SAVE"),
	SUCCESSFUL_UPDATE("SUCCESSFUL_UPDATE"),
	UNSUCCESSFUL_UPDATE("UNSUCCESSFUL_UPDATE"),
	SUCCESSFUL_DELETE("SUCCESSFUL_DELETE"),
	UNSUCCESSFUL_DELETE("UNSUCCESSFUL_DELETE"),
	GENERIC_TOT_REC_FOUND("GENERIC_TOT_REC_FOUND"),
	GENERIC_NO_REC_FOUND("GENERIC_NO_REC_FOUND"),
	LOGIN_SUCCESS("LOGIN_SUCCESS"),
	LOGIN_FAILURE("LOGIN_FAILURE"),
	LOGIN_EXIST("LOGIN_EXIST"),
	USERNAME_INVALID("USERNAME_INVALID"),
	PASSWORD_INVALID("PASSWORD_INVALID"),
	INVALID_USER_PERSON_ACCESS("INVALID_USER_PERSON_ACCESS"),
	UNEXPECTED_ERROR("UNEXPECTED_ERROR"),
	IDEAL_CODE(new Long(0)),
	VALUE_REQUIRED_CODE(new Long(1)),
	IVALID_VALUE_CODE(new Long(2)),
	FATEL_CODE(new Long(3)),
	NO_RECORD_CODE(new Long(4)),
	FAILURE_CODE(new Long(5)),
	UNAUTHORIZED(new Long(6));
	

	private String value;
	private Long longValue;

	private CodeEnum(String value) {
		this.value = value;
	}
	
	private CodeEnum(Long longValue){
		this.longValue= longValue;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Long getLongValue() {
		return longValue;
	}

	public void setLongValue(Long longValue) {
		this.longValue = longValue;
	}
	
}
